spring:
  application:
    name: accountservice

info:
  component: accountservice


server:
  port: 7766


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



cloud:
  services:
    registrationMethod: route

